version: '3'

services:
  truck-service:
    build: .
    command: python truck_service.py
    ports:
      - "5001:5001"

  shipment-service:
    build: .
    command: python shipment_service.py
    ports:
      - "5002:5002"

  driver-service:
    build: .
    command: python driver_service.py
    ports:
      - "5003:5003"
